### ISSUE TITLE
Test system

### ISSUE THREAD

**Issue by avsmal** [avsmal/circuitsat#1]
- run all tests from a folder
- collect statistics
- draw plots

**Comment by 1DarkLord1** [comment]
1. Подписать точки не номерами а названиями экземпляров задачи
2. Отсортировать (возможно аргумент --plot-sorted)
3. Сократить длинные названия функций CLI , например:
external-solver-runner --> run-external
internal-solver-runner --> run-internal
4. Выделить wildcard аргументов внешнего солвера в отдельную опцию --args
5. Научиться понимать ответ солвера (0, 10, 20) и как-то это выводить в статистике
6. Возможно, добавить аргумент --plot-title для выбора заголовка графика
7. Научиться выводит данные по запуску в текстовый файл, для возможности их дальнейшего использования
